enum CardType {
  VISA
  MASTERCARD
}

type User {
  email: String!
  hash: String!
}

type AvailableFeature {
  title: String!
}

type Bank {
  backer: String
  name: String!
  apr: String
  cardType: CardType
  noFees: Boolean
  description: String
  webUrl: String
  iosUrl: String
  androidUrl: String
  features: [String]!
  phone: String
  chat: String
  email: String
}

type Query {
  allBanks: [Bank]!
  allUsers: [User]!
  allAvailableFeatures: [AvailableFeature]!
  findBankByName(name: String!): Bank
  findUserByEmail(email: String!): User
}